DROP TABLE IF EXISTS books;

CREATE TABLE books (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id INT NOT NULL,
  title varchar(100) NOT NULL,
  author varchar(100) NOT NULL,
  price decimal(5,2) NOT NULL,
  _created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT books_ibfk_1 FOREIGN KEY (category_id) REFERENCES Categories (id)
);

INSERT INTO books VALUES 
   (1,1,'Dune','Frank Herber',19.99,'2024-02-19 15:40:36'),
   (2,2,'The Girl with the Dragon Tattoo','Stieg Larsson',15.99,'2024-02-19 15:40:36'),
   (3,3,'The Hobbit','J.R.R. Tolkien',12.99,'2024-02-19 15:40:36');
