DROP TABLE IF EXISTS categories;

CREATE TABLE categories (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL
);

INSERT INTO categories VALUES 
   (1,'Science Fiction'),
   (2,'Mystery'),
   (3,'Fantasy'),
   (4,'Non-Fiction');
