DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255),
  role VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  _created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users VALUES 
   (1,'test@test.com','$2b$10$Llunwy4lTK9h97LGKw9nh.3KFhEHBLYBHlzLsQ5.i02MShMv7MBDa','admin','2024-02-23 23:04:52','2024-02-23 23:04:52'),
   (2,'test@test1.com','$2b$10$Wxscbmut09pkETRYBjt4rOhSK9Mj0vnSoL7TLZCYYOCDZG6oLZ0/K','user','2024-02-27 00:01:54','2024-02-27 00:01:55'),
   (5,'test@test.com1','$2b$10$3pwb7b3Z3N4OlwACsgZ1QuU90QMcR4q06myNkJ.i.5DUXR8MiV2x2','user','2024-03-01 19:49:34','2024-03-01 19:49:35'),(7,'test1@test.com','$2b$10$dEulRnHaHplqMva1zSWwKuU6w5nHjfc3ZHpKp4vpuebX.Z9MyuYca','user','2024-03-01 23:51:08','2024-03-01 23:51:08'),(8,'test2@test.com','$2b$10$IMnZmp0mNBFxg3k03t5Gde4J5U4C9yHBvPGw.9DyNkJ7iipO5Yrm6','user','2024-03-02 00:02:03','2024-03-02 00:02:04'),(9,'test6@test.com','$2b$10$XMPjo2aDPWXdiKHhna3MLOG.6PSruL0PalcyJC2u86bzRFUyGYFFC','user','2024-03-02 00:04:21','2024-03-02 00:04:21'),(10,'test@test99.com','$2b$10$PJaodNPy.GqzlcJszlFnteE0Spj5f5jTWIX4F.SQhg9kmxwEOgLTK','user','2024-03-07 15:44:32','2024-03-07 15:44:33'),(11,'test@88test.com','$2b$10$c7Ec0qLAAxr5YGxxgOtVA.skikkPEfeWIMlLVBlLO26itqFtUkVkW','user','2024-03-07 19:31:46','2024-03-07 19:31:45'),(12,'test@test34.com','$2b$10$HGSo9MensNvCKV07tHBh2exzLmPO2Ou2WSeMZdydYO98tZilxYm02','user','2024-03-07 20:14:47','2024-03-07 20:14:47');
